name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - ".github/**/*.yml"
      - "*.json"
      - "*.js"

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-slim
    timeout-minutes: 12
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - name: Check format
        run: npm run lint
  test:
    name: Testing
    needs: lint
    timeout-minutes: 12
    strategy:
      matrix:
        os:
          [
            ubuntu-latest,
            ubuntu-24.04,
            ubuntu-26.04,
            ubuntu-24.04-arm,
            ubuntu-26.04-arm,
            macos-latest,
            macos-26-intel,
            windows-11-arm,
            windows-2025,
            windows-latest,
          ]
        node-version: [22, 24, 26, latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run test
  bench:
    name: Benchmarking
    needs: [lint, test]
    timeout-minutes: 12
    strategy:
      matrix:
        os:
          [
            ubuntu-24.04,
            ubuntu-26.04,
            ubuntu-24.04-arm,
            ubuntu-26.04-arm,
            macos-latest,
            macos-26-intel,
            windows-11-arm,
            windows-2025,
            windows-latest,
          ]
        node-version: [22, 24, 26, latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run bench
