name: Test

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/*.yml"
      - "biome.json"
      - "*.js"
      - "package.json"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/*.yml"
      - "biome.json"
      - "*.js"
      - "package.json"

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
      - run: npm ci
      - name: Check format
        run: npm run lint
  build:
    name: Testing
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        node-version: [22, 24]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run test
